apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "terragrunt_demo"
  annotations:
    github.com/project-slug: gabdzo/terragrunt_demo
spec:
  type: service
  owner: user:guest
  lifecycle: experimental